//Country names which vary between the different api's used
export const countryNames: Record<string, string> = {
  "Bosnia and Herzegovina": "Bosnia",
  Burma: "Myanmar",
  "Congo (Brazzaville)": "Congo",
  "Congo (Kinshasa)": "DRC",
  Eswatini: "Swaziland",
  "Holy See": "Holy See (Vatican City State)",
  "Korea, South": "S. Korea",
  Laos: "Lao People's Democratic Republic",
  Libya: "Libyan Arab Jamahiriya",
  "North Macedonia": "Macedonia",
  Syria: "Syrian Arab Republic",
  "Taiwan*": "Taiwan",
  US: "USA",
  "United Arab Emirates": "UAE",
  "United Kingdom": "UK",
  "West Bank and Gaza": "Palestine",
  "Cote d'Ivoire": "Côte d'Ivoire",
};
